#https://xaoxuu.com/wiki/stellar

#é»˜è®¤ç”Ÿæˆ Open Graph æ ‡ç­¾ï¼Œå¦‚æœæ‚¨ä¸å¸Œæœ›ç”Ÿæˆå®ƒï¼Œå¯ä»¥åœ¨ä¸»é¢˜é…ç½®æ–‡ä»¶ä¸­å…³é—­ï¼š
open_graph:
  enable: true
  twitter_id: # for open_graph meta

#æ ¹æ® tags ä½œä¸ºå…³é”®è¯ä¸ºæ¯ä¸€ç¯‡æ–‡ç« åœ¨çº¿æœç´¢å°é¢ï¼š
article:
  auto_cover: true

#---
 ## æœ¬åœ°å›¾ç‰‡è·¯å¾„ä¸º blog/source/assets/xaoxuu/blog/2020-0927a@1x.svg
 ## ä¹Ÿå¯ä»¥ç›´æ¥å¼•ç”¨å›¾ç‰‡ç›´é“¾ https://xxx.jpg
 #cover: /assets/xaoxuu/blog/2020-0927a@1x.svg
 #---

 #---
   #cover: /assets/xaoxuu/blog/2020-0927a@1x.svg # å¿…é€‰
   #poster: # æµ·æŠ¥ï¼ˆå¯é€‰ï¼Œå…¨å›¾å°é¢å¡ç‰‡ï¼‰
   #  topic: æ ‡é¢˜ä¸Šæ–¹çš„å°å­— # å¯é€‰
   #  headline: å¤§æ ‡é¢˜ # å¿…é€‰
   #  caption: æ ‡é¢˜ä¸‹æ–¹çš„å°å­— # å¯é€‰
   #  color: æ ‡é¢˜é¢œè‰² # å¯é€‰ï¼Œé»˜è®¤ä¸ºè·Ÿéšä¸»é¢˜çš„åŠ¨æ€é¢œè‰² # white,red...
   #---

#è‡ªåŠ¨ä»æ–‡ç« å†…å®¹æˆªå–ä¸€å®šå­—æ•°çš„æ–‡å­—ä½œä¸ºæ‘˜è¦ï¼Œå¯ä»¥è¿™æ ·è®¾ç½®ï¼š
article:
   auto_excerpt: 50

#ç›¸å…³æ–‡ç« æ¨è
article:
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 

#å¼•ç”¨
#---
 #references:
 #  - title: 'å¿ƒè·³ä¹‹æ—…â€”ğŸ’—â€”iOSç”¨æ‰‹æœºæ‘„åƒå¤´æ£€æµ‹å¿ƒç‡(PPG)'
 #    url: https://punmy.cn/2016/07/28/15231176397746.html
 #  - title: 'PPGå…‰ç”µå®¹ç§¯è„‰ææ³¢æè®°æ³•æŠ€æœ¯æ¦‚å†µ'
 #    url: https://www.jianshu.com/p/695c131abfa5
 #  ...
 #---

#å¯¼èˆªæ 
sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[ç¬”è®°](/notes/)'
    more: '[æ›´å¤š](/more/)'
  logo:
    title: '[<img no-lazy height="32px" src="https://cdn.jsdelivr.net/gh/kayleh/logo/logo.png"/>](/)'

# æ–‡ç« æœç´¢
search:
  service: local_search # local_search, todo...
  local_search: # åœ¨ front-matter ä¸­è®¾ç½® indexing:false æ¥é¿å…è¢«æœç´¢ç´¢å¼•
    field: all # post, page, all
    path: /search.json # æœç´¢æ–‡ä»¶å­˜æ”¾ä½ç½®
    content: true # æ˜¯å¦æœç´¢å†…å®¹
    codeblock: true # æ˜¯å¦æœç´¢ä»£ç å—ï¼ˆéœ€è¦content: true)

#footer
footer:
  social:
#    github:
#      icon: '<img src="/assets/placeholder/social/08a41b181ce68.svg"/>'
#      url: https://
#    music:
#      icon: '<img src="/assets/placeholder/social/3845874.svg"/>'
#      url: https://
#    unsplash:
#      icon: '<img src="/assets/placeholder/social/3616429.svg"/>'
#      url: https://
#    comments:
#      icon: '<img src="/assets/placeholder/social/942ebbf1a4b91.svg"/>'
#      url: https://

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: Kayleh/kayleh.top.giscus # [åœ¨æ­¤è¾“å…¥ä»“åº“]
    data-repo-id: R_kgDOJrPWjA # [åœ¨æ­¤è¾“å…¥ä»“åº“ ID]
    data-category: announcements # [åœ¨æ­¤è¾“å…¥åˆ†ç±»å]
    data-category-id: DIC_kwDOJrPWjM4CW9R6
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

#font:
style:
  font-size:
    root: 16px
    body: .9375rem # 15px
    code: 85% # 14px
    codeblock: 0.8125rem # 13px
  font-family:
    logo: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

#ç«™ç‚¹åœ°å›¾
sitemap:
  'åšå®¢':
    - '[æ ‡ç­¾](/tags/)'
    - '[å½’æ¡£](/archives/)'
  'æ›´å¤š':
     - '[å…³äºæœ¬ç«™](/)'
#    - '[GitHub](/)'
content: | # æ”¯æŒ Markdown æ ¼å¼
  æœ¬ç«™ç”± [@kayleh](/) åˆ›å»ºã€‚
  æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
# ä¸»é¢˜ç”¨æˆ·è¶Šå¤šï¼Œå¼€å‘è€…ç»´æŠ¤å’Œæ›´æ–°çš„ç§¯ææ€§å°±è¶Šé«˜ï¼Œå¦‚æœæ‚¨å–œæ¬¢æœ¬ä¸»é¢˜ï¼Œè¯·åœ¨é€‚å½“çš„ä½ç½®æ˜¾ç¤ºä¸»é¢˜ä¿¡æ¯å’Œä»“åº“é“¾æ¥ä»¥è¡¨æ”¯æŒã€‚

#æ‡’åŠ è½½
# é»˜è®¤æ‰“å¼€
lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade
